name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore Lampac.sln

    - name: Build
      run: dotnet build Lampac.sln --no-restore --configuration Release
